import React from 'react';
import '../style/App.css';
import Header from './Header';
import Footer from './Footer';
import Project from './Project';
import About from './About';

function App() {
  return (
    <div className="App">
      <Header/>
      <div id="projects">
        <Project styleType='ProjectFullW' title='Mordechi Marches to Manchuria' modalNum='0' imageLink="https://raw.githubusercontent.com/fasky/Images/master/MordechiTitle.PNG" secondImage="https://raw.githubusercontent.com/fasky/Images/master/MordechiMap.PNG" description="Second co-op project. Regards the story of a Russian Jew conscripted into the Tsar's army. Re-engineered and modernized a history site using React, JS, GraphQL, Node.js, and Airtable. Full-stack, remote. Database work, research, server development, front-end development. - <a target='_blank' href = 'https://mordechi-fasky.herokuapp.com/'>Click Here!</a> May take a minute to start up."/>
        <Project styleType='ProjectFullW' title='Tiger Center' modalNum='1' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/TC.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/TCC.PNG" description="A student designed and run website built with Angular and Java. A single page web-app bringing together multiple school services onto one accessible page. Worked as a web developer, on co-op for Fall 2019. Worked with a team at the Student IT Office at RIT - <a target='_blank' href = 'https://tigercenter.rit.edu/tigerCenterApp/login_shib/tc/homepage'>Tiger Center</a>"/>
        <Project styleType='ProjectFullW' title='Skreeta Skraw' modalNum='2' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/logo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/skreetaMainMenu.PNG" description="<a target='_blank' href='https://fasky.itch.io/skreeta-skraw'>Play Here</a>. A Trouble-like board game made by family, now available digitally. Made in a few days in Unity. Features local multiplayer and singleplayer games against AI."/>
        <Project styleType='ProjectFullW' title='National Park Map' modalNum='3' imageLink="https://www.nps.gov/common/commonspot/templates/images/logos/nps_social_image_02.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/NatParks.PNG" description="<a target='_blank' href='https://330projects.faskyport.com/project2/project2.html'>Web Page</a> - National Park and Weather Map - A web app using Leaflet map API, Nat Parks API, and OpenWeather API to deliver a national park lookup and info map."/>
        <Project styleType='ProjectHalf' title='Audio Visualizer' modalNum='4' imageLink="https://raw.githubusercontent.com/fasky/Images/master/AudioVis.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/AudioVisMore.png" description="<a target='_blank' href='https://330projects.faskyport.com/project1/'>Link</a> - An audio visualizer made with ES6/JS, HTML, CSS, and Pure CSS. Works with Chrome and Firefox."/>
        <Project styleType='ProjectHalf' title='War Clicker' modalNum='5' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/ClickerLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/clicker.PNG" description="<a target='_blank' href='https://fasky.itch.io/war-clicker'>War Clicker</a> - <a target='_blank' href = 'https://github.com/fasky/war-clicker'>Git<a/> - A Simple Strategy Game. Made in HTML, CSS, and JS. Collect gold and build units to try and take over the enemy tiles. Features multiple scenarios, difficulties, building types, and a music player."/>
        <Project styleType='ProjectHalf' title='Amazon Blink' modalNum='6' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/amazon.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/amazon.jpg" description="UI/UX Project - Amazon Blink - teleport service concept. Handled wireframing, layout, prototyping, etc. <a target='_blank' href='https://drive.google.com/file/d/19VtKvwXHxr3S2BEw9krDEGFfvDfFJMr8/view?usp=sharing'>Design Doc</a>"/>
        <Project styleType='ProjectHalf' title='Spear of Cassius' modalNum='7' imageLink="https://raw.githubusercontent.com/fasky/Images/master/spearOfCassius.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/Spear.PNG" description="<a target='_blank' href='https://fasky.itch.io/spear-of-cassius'>Game Page</a> - A short fighting game with a side scrolling segment. Made in PixiJS, lone developer. <a target='_blank' href = 'https://github.com/fasky/spear-of-cassius'>Git</a>"/>
        <Project styleType='ProjectFullW' title='Dark Plane' modalNum='8' imageLink="https://raw.githubusercontent.com/fasky/Images/master/DarkPlaneLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/DarkPlane.PNG" description="<a target='_blank' href='https://fasky.itch.io/dark-plane'>Short Prototype</a> - Earthbound-like game abut a boy accidently revealing a hidden plane of reality and having to turn everything back to normal. Being developed in Unity/C#."/>
        <Project styleType='ProjectHalf' title='The Void' modalNum='9' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/voidLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/mediaOldTopLevel/thevoid.png" description="<a target='_blank' href='https://www.youtube.com/watch?v=3P57vzQRzuA'>The Void</a> - A dungeon crawling adventure through four distinct areas, each based on an element(Earth, Wind, etc.). With special abilities and pickups, the player fights their way to the final dungeon so they can return home. Made in GameMaker."/>
        <Project styleType='ProjectHalf' title='Gravity Joe' modalNum='10' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GravJoeLogo.PNG" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GravJoe.png" description="Gravity Joe - 2D platformer puzzle-ish game. Rotate the level to reach the exit. Avoid spikes. Handled bugfixes, QA, basic art - <a target='_blank' href='https://drive.google.com/file/d/1IOSO6miV6KS63znpcVErRXCu8qxA4TAZ/view?usp=sharing'>Short Doc</a> - <a target='_blank' href='https://drive.google.com/file/d/1P9ISi1wclZcAYHkN-lFE2PuY6yz_hTbt/view?usp=sharing'>Download</a> - <a target='_blank' href='https://github.com/louisgv/GravityJoe'>GitHub</a>"/>
        <Project styleType='ProjectThird' title='Bethesda Mods' modalNum='11' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/beth.jpg" secondImage="https://mods.bethesda.net/content/a20627c3-e618-445f-b30a-06b30ecff8e4_preview_754398_10395904557244347534_large.png" description="<a target='_blank' href='https://bethesda.net/en/mods/fallout4?author_username=Fasky&number_results=20&order=desc&page=1&product=fallout4'>Creation Club Page</a> - A small collection of mods made for Bethesda Games. Thousands of views and downloads on Bethesda's website. Downloads: <a target='_blank' href='https://github.com/fasky/Images/blob/master/mediaOldTopLevel/mods/Skyrim/ruins.esp'>Skyrim Ruins</a>, <a target='_blank' href='https://github.com/fasky/Images/blob/master/mediaOldTopLevel/mods/Skyrim/test.esp'>Skyrim Riverwood Raider Hideout</a>, <a target='_blank' href='https://github.com/fasky/Images/blob/master/mediaOldTopLevel/mods/F3/memorialraiders.esp'>Fallout 3 Memorial Raiders</a>, <a target='_blank' href='https://github.com/fasky/Images/blob/master/mediaOldTopLevel/mods/F3/sewerfinding.esp'>Fallout 3 Sewer Hideout</a>."/>
        <Project styleType='ProjectThird' title='Misteaks Were Made' modalNum='12' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MisteaksLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/Misteaks.png" description="Misteaks Were Made - Small game for class. Worked in a group. Handled most of the art. - <a target='_blank' href='https://drive.google.com/file/d/1-564RkcZk7a4wUp6hf2eFtEUYg8q-Rg8/view?usp=sharing'>Short Doc</a> - <a target='_blank' href='https://drive.google.com/file/d/1OfS0A25MFAQ3L1dl5RdaZ7BmS29RAwBY/view?usp=sharing'>Download</a>"/>
        <Project styleType='ProjectThird' title='Ghostly Gauntlet' modalNum='13' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGlogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGBoard.png" description="Ghostly Gauntlet - Board game based on Harry Potter for class. Handled rule creation and card/board design - <a target='_blank' href='https://drive.google.com/file/d/1PpvNFZhksNnMFRnffgiiLHeflC2YZN9z/view?usp=sharing'>Short Doc</a>"/>
        <Project styleType='ProjectFullW' title='Asteroids' modalNum='14' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/asLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/Asteroids.PNG" description="<a target='_blank' href='https://github.com/fasky/unity-master/tree/master/Asteroids-Code'>Git</a> - An Asteroids recreation in the theme of Star Wars - specifically Attack of the Clones. Made in Unity, for practice with vehicles and coding collisions."/>
        <Project styleType='ProjectThird' title='Skyrim Mod' modalNum='15' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" description="Short Skyrim Quest - Dank Places - Practice in level design. Practiced sketching, modular design, documentation, scripting, pacing, balancing, making interesting spaces, etc. - <a target='_blank' href='https://drive.google.com/file/d/1Cawdz6ghJPPaZHuDPuKf5qiYsstkVD1E/view?usp=sharing'>Doc with video link</a>"/>
        <Project styleType='ProjectThird' title='Pac-Man Recreation' modalNum='16' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/pacMan.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/play.png" description="<a target='_blank' href = 'https://www.youtube.com/watch?v=8mIvspCB77Q'>Pac-Man Recreation</a> - a semi-accurate recreation of the original Pac-Man in GameMaker."/>
        <Project styleType='ProjectThird' title='Plasma Peasant' modalNum='17' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasma.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasmaPlay.PNG" description="<a target='_blank' href='https://github.com/Therobodavo/Plasma-Peasant'>Git Repo</a> - A top down wave-based survival game. Survive against robotic enemies as a peasant from the past, stuck in the future. Shoot enemies, pick up powerups, and make it as far as you can. Includes a level editor for customizing level layouts."/>
        <Project styleType='ProjectHalf' title='Fasanella World' modalNum='18' imageLink="https://raw.githubusercontent.com/fasky/Images/master/world-image.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/Fasanella_World.PNG" description="<a target='_blank' href='https://github.com/fasky/unity-master/tree/master/Fasanella_World_Code'>Git</a> - Result of a class focused on autonomous agents. This is a forest made in Unity/C# populated by flockers, path followers, and flow field followers."/>
        <Project styleType='ProjectHalf' title='The Senate' modalNum='19' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/senate.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/senatePlay.jpg" description="The Senate - A Shoot 'em up made in Unity. Mainly a design project. Based on Star Wars. Includes opening animation. <a target='_blank' href='https://fasky.itch.io/the-senate'>Download here</a>."/>
        <Project styleType='ProjectThird' title='Far Cry 3 Map' modalNum='20' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/fc3.jpg" secondImage="https://fasanellak.files.wordpress.com/2016/01/far-cry-3-01-31-2016-14-16-48-031.png?w=2000&h=" description="A custom map for Far Cry 3 made in the FC3 level editor. Result of a session playing with level design and open ended paths to the goal. <a target='_blank' href='https://fasanellak.wordpress.com/2016/01/31/far-cry-3-map-editor-sunken-atoll/'>More Info.</a>"/>
        <Project styleType='ProjectThird' title='GitHub Profile' modalNum='21' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" description="<a target='_blank' href='https://github.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectThird' title='Sketchfab Profile' modalNum='22' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" description="<a target='_blank' href='https://sketchfab.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectThird' title='Itch Profile' modalNum='23' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" description="<a target='_blank' href='https://fasky.itch.io/'>Click Here.</a>"/>
        <Project styleType='ProjectThird' title='GameJolt Profile' modalNum='24' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" description="<a target='_blank' href='https://gamejolt.com/@fasky'>Click Here.</a>"/>
        <Project styleType='ProjectThird' title='NewGrounds Profile' modalNum='25' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" description="<a target='_blank' href='https://fasky.newgrounds.com/'>Click Here.</a>"/>

        {/* Proj Comps for phone Screens */}
        <Project styleType='ProjectFullWShowPhone' title='Audio Visualizer' modalNum='38' imageLink="https://raw.githubusercontent.com/fasky/Images/master/AudioVis.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/AudioVisMore.png" description="<a target='_blank' href='https://330projects.faskyport.com/project1/'>Link</a> - An audio visualizer made with ES6/JS, HTML, CSS, and Pure CSS. Works with Chrome and Firefox."/>
        <Project styleType='ProjectFullWShowPhone' title='War Clicker' modalNum='39' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/ClickerLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/clicker.PNG" description="<a target='_blank' href='https://fasky.itch.io/war-clicker'>War Clicker</a> - <a target='_blank' href = 'https://github.com/fasky/war-clicker'>Git<a/> - A Simple Strategy Game. Made in HTML, CSS, and JS. Collect gold and build units to try and take over the enemy tiles. Features multiple scenarios, difficulties, building types, and a music player."/>
        <Project styleType='ProjectFullWShowPhone' title='Amazon Blink' modalNum='40' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/amazon.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/amazon.jpg" description="UI/UX Project - Amazon Blink - teleport service concept. Handled wireframing, layout, prototyping, etc. <a target='_blank' href='https://drive.google.com/file/d/19VtKvwXHxr3S2BEw9krDEGFfvDfFJMr8/view?usp=sharing'>Design Doc</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Spear of Cassius' modalNum='41' imageLink="https://raw.githubusercontent.com/fasky/Images/master/spearOfCassius.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/Spear.PNG" description="<a target='_blank' href='https://fasky.itch.io/spear-of-cassius'>Game Page</a> - A short fighting game with a side scrolling segment. Made in PixiJS, lone developer. <a target='_blank' href = 'https://github.com/fasky/spear-of-cassius'>Git</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Fasanella World' modalNum='42' imageLink="https://raw.githubusercontent.com/fasky/Images/master/world-image.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/Fasanella_World.PNG" description="<a target='_blank' href='https://github.com/fasky/unity-master/tree/master/Fasanella_World_Code'>Git</a> - Result of a class focused on autonomous agents. This is a forest made in Unity/C# populated by flockers, path followers, and flow field followers."/>
        <Project styleType='ProjectFullWShowPhone' title='The Senate' modalNum='43' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/senate.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/senatePlay.jpg" description="The Senate - A Shoot 'em up made in Unity. Mainly a design project. Based on Star Wars. Includes opening animation. <a target='_blank' href='https://fasky.itch.io/the-senate'>Download here</a>."/>
        <Project styleType='ProjectFullWShowPhone' title='Bethesda Mods' modalNum='44' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/beth.jpg" secondImage="https://mods.bethesda.net/content/a20627c3-e618-445f-b30a-06b30ecff8e4_preview_754398_10395904557244347534_large.png" description="<a href='https://people.rit.edu/kmf7094/igme110/mods.html'>Collection</a> - <a target='_blank' href='https://bethesda.net/en/mods/fallout4?author_username=Fasky&number_results=20&order=desc&page=1&product=fallout4'>Creation Club Page</a> - A small collection of mods made for Bethesda Games. Thousands of views and downloads on Bethesda's website."/>
        <Project styleType='ProjectFullWShowPhone' title='Misteaks Were Made' modalNum='45' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MisteaksLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/Misteaks.png" description="Misteaks Were Made - Small game for class. Worked in a group. Handled most of the art. - <a target='_blank' href='https://drive.google.com/file/d/1-564RkcZk7a4wUp6hf2eFtEUYg8q-Rg8/view?usp=sharing'>Short Doc</a> - <a target='_blank' href='https://drive.google.com/file/d/1OfS0A25MFAQ3L1dl5RdaZ7BmS29RAwBY/view?usp=sharing'>Download</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Ghostly Gauntlet' modalNum='46' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGlogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGBoard.png" description="Ghostly Gauntlet - Board game based on Harry Potter for class. Handled rule creation and card/board design - <a target='_blank' href='https://drive.google.com/file/d/1PpvNFZhksNnMFRnffgiiLHeflC2YZN9z/view?usp=sharing'>Short Doc</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Skyrim Mod' modalNum='47' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" description="Short Skyrim Quest - Dank Places - Practice in level design. Practiced sketching, modular design, documentation, scripting, pacing, balancing, making interesting spaces, etc. - <a target='_blank' href='https://drive.google.com/file/d/1Cawdz6ghJPPaZHuDPuKf5qiYsstkVD1E/view?usp=sharing'>Doc with video link</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Pac-Man Recreation' modalNum='48' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/pacMan.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/play.png" description="<a target='_blank' href = 'https://www.youtube.com/watch?v=8mIvspCB77Q'>Pac-Man Recreation</a> - a semi-accurate recreation of the original Pac-Man in GameMaker."/>
        <Project styleType='ProjectFullWShowPhone' title='Plasma Peasant' modalNum='49' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasma.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasmaPlay.PNG" description="<a target='_blank' href='https://github.com/Therobodavo/Plasma-Peasant'>Git Repo</a> - A top down wave-based survival game. Survive against robotic enemies as a peasant from the past, stuck in the future. Shoot enemies, pick up powerups, and make it as far as you can. Includes a level editor for customizing level layouts."/>
        <Project styleType='ProjectFullWShowPhone' title='Far Cry 3 Map' modalNum='50' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/fc3.jpg" secondImage="https://fasanellak.files.wordpress.com/2016/01/far-cry-3-01-31-2016-14-16-48-031.png?w=2000&h=" description="A custom map for Far Cry 3 made in the FC3 level editor. Result of a session playing with level design and open ended paths to the goal. <a target='_blank' href='https://fasanellak.wordpress.com/2016/01/31/far-cry-3-map-editor-sunken-atoll/'>More Info.</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='GitHub Profile' modalNum='51' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" description="<a target='_blank' href='https://github.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Sketchfab Profile' modalNum='52' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" description="<a target='_blank' href='https://sketchfab.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='Itch Profile' modalNum='53' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" description="<a target='_blank' href='https://fasky.itch.io/'>Click Here.</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='GameJolt Profile' modalNum='54' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" description="<a target='_blank' href='https://gamejolt.com/@fasky'>Click Here.</a>"/>
        <Project styleType='ProjectFullWShowPhone' title='NewGroundsProfle' modalNum='55' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" description="<a target='_blank' href='https://fasky.newgrounds.com/'>Click Here.</a>"/>

        {/* Proj comps for tablet  */}
        <Project styleType='ProjectHalfShowTablet' title='Bethesda Mods' modalNum='26' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/beth.jpg" secondImage="https://mods.bethesda.net/content/a20627c3-e618-445f-b30a-06b30ecff8e4_preview_754398_10395904557244347534_large.png" description="<a href='https://people.rit.edu/kmf7094/igme110/mods.html'>Collection</a> - <a target='_blank' href='https://bethesda.net/en/mods/fallout4?author_username=Fasky&number_results=20&order=desc&page=1&product=fallout4'>Creation Club Page</a> - A small collection of mods made for Bethesda Games. Thousands of views and downloads on Bethesda's website."/>
        <Project styleType='ProjectHalfShowTablet' title='Misteaks Were Made' modalNum='27' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MisteaksLogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/Misteaks.png" description="Misteaks Were Made - Small game for class. Worked in a group. Handled most of the art. - <a target='_blank' href='https://drive.google.com/file/d/1-564RkcZk7a4wUp6hf2eFtEUYg8q-Rg8/view?usp=sharing'>Short Doc</a> - <a target='_blank' href='https://drive.google.com/file/d/1OfS0A25MFAQ3L1dl5RdaZ7BmS29RAwBY/view?usp=sharing'>Download</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='Ghostly Gauntlet' modalNum='28' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGlogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/GGBoard.png" description="Ghostly Gauntlet - Board game based on Harry Potter for class. Handled rule creation and card/board design - <a target='_blank' href='https://drive.google.com/file/d/1PpvNFZhksNnMFRnffgiiLHeflC2YZN9z/view?usp=sharing'>Short Doc</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='Skyrim Mod' modalNum='29' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/danklogo.png" description="Short Skyrim Quest - Dank Places - Practice in level design. Practiced sketching, modular design, documentation, scripting, pacing, balancing, making interesting spaces, etc. - <a target='_blank' href='https://drive.google.com/file/d/1Cawdz6ghJPPaZHuDPuKf5qiYsstkVD1E/view?usp=sharing'>Doc with video link</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='Pac-Man Recreation' modalNum='30' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/pacMan.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/play.png" description="<a target='_blank' href = 'https://www.youtube.com/watch?v=8mIvspCB77Q'>Pac-Man Recreation</a> - a semi-accurate recreation of the original Pac-Man in GameMaker."/>
        <Project styleType='ProjectHalfShowTablet' title='Plasma Peasant' modalNum='31' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasma.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/plasmaPlay.PNG" description="<a target='_blank' href='https://github.com/Therobodavo/Plasma-Peasant'>Git Repo</a> - A top down wave-based survival game. Survive against robotic enemies as a peasant from the past, stuck in the future. Shoot enemies, pick up powerups, and make it as far as you can. Includes a level editor for customizing level layouts."/>
        <Project styleType='ProjectHalfShowTablet' title='Far Cry 3 Map' modalNum='32' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/fc3.jpg" secondImage="https://fasanellak.files.wordpress.com/2016/01/far-cry-3-01-31-2016-14-16-48-031.png?w=2000&h=" description="A custom map for Far Cry 3 made in the FC3 level editor. Result of a session playing with level design and open ended paths to the goal. <a target='_blank' href='https://fasanellak.wordpress.com/2016/01/31/far-cry-3-map-editor-sunken-atoll/'>More Info.</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='GitHub Profile' modalNum='33' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/git.jpg" description="<a target='_blank' href='https://github.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='Sketchfab Profile' modalNum='34' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/halo2.jpg" description="<a target='_blank' href='https://sketchfab.com/fasky'>Click Here.</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='Itch Profile' modalNum='35' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/itch-io.png" description="<a target='_blank' href='https://fasky.itch.io/'>Click Here.</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='GameJolt Profile' modalNum='36' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/MPuPjZQ.png" description="<a target='_blank' href='https://gamejolt.com/@fasky'>Click Here.</a>"/>
        <Project styleType='ProjectHalfShowTablet' title='NewGroundsProfle' modalNum='37' imageLink="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" secondImage="https://raw.githubusercontent.com/fasky/Images/master/PortfolioStuff/dl-tank.gif" description="<a target='_blank' href='https://fasky.newgrounds.com/'>Click Here.</a>"/>

      </div>
      <div id="aboutSection">
        <About/>
      </div>
      <Footer/>
    </div>
  );
}

export default App;
